import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
   game: {
      backgroundColor: 'gray',
      //overflow: 'hidden',
      padding: 10,
      alignSelf: 'center',
      height: 400,
      width: 400,
      borderRadius: 400,
   },
   score: {textAlign: 'center', color: 'white', fontSize: 30},
   play: {
      backgroundColor: 'black',
      borderRadius: 100,
      justifyContent: 'center',
      alignItems: 'center',
      textAlign: 'center',
      height: 90,
      width: 90,
      alignSelf: 'center',
      position: 'absolute',
      zIndex: 1,
      top: 155,
   },
   colors_row: {
      flex: 0.5,
      flexDirection: 'row',
      justifyContent: 'space-between',
   },
   red_button: {
      borderTopRightRadius: 200,
      flex: 0.5,
      borderWidth: 10,
      flexDirection: 'row',
   },
   red_button_inverted: {
      backgroundColor: 'gray',
      height: 50,
      width: 50,
      borderTopRightRadius: 200,
      borderColor: 'gray',
      borderWidth: 5,
      transform: [{translateY: 10}, {translateX: -10}],
      alignSelf: 'flex-end',
   },
   blue_button: {borderBottomRightRadius: 200, flex: 0.5, borderWidth: 10},
   blue_button_inverted: {
      backgroundColor: 'gray',
      height: 50,
      width: 50,
      alignSelf: 'flex-start',
      borderBottomRightRadius: 200,
      borderColor: 'gray',
      borderWidth: 5,
      transform: [{translateY: -10}, {translateX: -10}],
   },
   green_button: {
      borderTopLeftRadius: 200,
      borderBottomRightRadius: -100,
      flex: 0.5,
      borderWidth: 10,
      flexDirection: 'row',
      justifyContent: 'flex-end',
   },
   green_button_inverted: {
      backgroundColor: 'gray',
      height: 50,
      width: 50,
      borderTopLeftRadius: 200,
      borderColor: 'gray',
      borderWidth: 5,
      transform: [{translateY: 10}, {translateX: 10}],
      alignSelf: 'flex-end',
   },
   yellow_button: {borderBottomLeftRadius: 200, flex: 0.5, borderWidth: 10},
   yellow_button_inverted: {
      backgroundColor: 'gray',
      height: 50,
      width: 50,
      borderBottomLeftRadius: 200,
      borderColor: 'gray',
      borderWidth: 5,
      transform: [{translateY: -10}, {translateX: 10}],
      alignSelf: 'flex-end',
   },
});

export default styles;
